### ISSUE TITLE
카드 기본 화면 구현

### ISSUE THREAD

**Issue by choco-tyranno** [choco-tyranno/team-tree#1]
기본 메인 화면을 구성한다.

카드 추가, 삭제, 이동, 플립, 저장, 상태 캐시(카드 level, 레이어 level), 영속성부여를 구현.

***

## Task List 
* UI
- [x] upper section main title floating button
- [x] Container item recyclerview
- [x] Container item
- [x] Card item
- [x] Card attributes
- [x] bottom section floating button
- [x] Card animation

* Presentation
- [x] MainActivity
- [x] ViewModel
- [x] ContainerRvAdapter
- [x] CardRvAdapter

* Data
- [x] Room
- [x] DAO
- [x] Repository
- [x] Entity
- [x] DTO

* 카드 추가
- [x] 하단 플로팅 버튼 드래그/드랍 기능
- [x] 드랍시 해당 위치로 카드 추가
- [x] 로컬 DB에서 데이터 추가

* 카드 삭제
- [x] 롱터치+제자리 터치 업시 삭제 버튼 팝업
- [x] 다른 곳 터치시 삭제버튼 사라짐
- [x] 삭제 기능(해당 카드와 그 카드에 종속된 하위 카드들 함께 삭제)
- [x] 삭제 진행시 확인창
- [x] 로컬 DB에서 데이터 삭제
